In [2]:
import pandas as pd

ALL_TOKENS = pd.read_csv('Data\CORPUS\FULL_CORPUS.csv')

<>:3: SyntaxWarning: invalid escape sequence '\C'
<>:3: SyntaxWarning: invalid escape sequence '\C'
C:\Users\school\AppData\Local\Temp\ipykernel_73712\2844328.py:3: SyntaxWarning: invalid escape sequence '\C'
  ALL_TOKENS = pd.read_csv('Data\CORPUS\FULL_CORPUS.csv')
C:\Users\school\AppData\Local\Temp\ipykernel_73712\2844328.py:3: DtypeWarning: Columns (5,6,9) have mixed types. Specify dtype option on import or set low_memory=False.
  ALL_TOKENS = pd.read_csv('Data\CORPUS\FULL_CORPUS.csv')

# VOCAB

In [3]:
VOCAB = ALL_TOKENS.term_str.value_counts().to_frame('n')
VOCAB.index.name = 'term_str'

In [4]:
import numpy as np

VOCAB = ALL_TOKENS.term_str.value_counts().to_frame('n')
VOCAB.index.name = 'term_str'
VOCAB['p'] = VOCAB.n / VOCAB.n.sum()
VOCAB['i'] = -np.log2(VOCAB.p)
VOCAB['n_chars'] = VOCAB.index.str.len()
VOCAB

               n         p          i  n_chars
term_str
the        36126  0.056064   4.156784        3
and        22280  0.034576   4.854073        3
to         18949  0.029407   5.087700        2
of         17802  0.027627   5.177783        2
i          15207  0.023600   5.405086        1
...          ...       ...        ...      ...
houseto        1  0.000002  19.297534        7
mopboard       1  0.000002  19.297534        8
slaps          1  0.000002  19.297534        5
tramples       1  0.000002  19.297534        8
arabesque      1  0.000002  19.297534        9

[21504 rows x 4 columns]

In [5]:
VOCAB['max_pos_group'] = ALL_TOKENS[['term_str','pos_group']].value_counts().unstack(fill_value=0).idxmax(1)
VOCAB['max_pos'] = ALL_TOKENS[['term_str','pos']].value_counts().unstack(fill_value=0).idxmax(1)
VOCAB

               n         p          i  n_chars max_pos_group max_pos
term_str
the        36126  0.056064   4.156784        3            DT      DT
and        22280  0.034576   4.854073        3            CC      CC
to         18949  0.029407   5.087700        2            TO      TO
of         17802  0.027627   5.177783        2            IN      IN
i          15207  0.023600   5.405086        1            PR     PRP
...          ...       ...        ...      ...           ...     ...
houseto        1  0.000002  19.297534        7           NaN     NaN
mopboard       1  0.000002  19.297534        8           NaN     NaN
slaps          1  0.000002  19.297534        5           NaN     NaN
tramples       1  0.000002  19.297534        8           NaN     NaN
arabesque      1  0.000002  19.297534        9           NaN     NaN

[21504 rows x 6 columns]

In [6]:
TPM1 = ALL_TOKENS[['term_str','pos_group']].value_counts().unstack()
TPM1
VOCAB['n_pos_group'] = TPM1.count(1)
TPM2 = ALL_TOKENS[['term_str','pos']].value_counts().unstack()
VOCAB['n_pos'] = TPM2.count(1)

In [7]:
import nltk
nltk.download('stopwords')
sw = pd.DataFrame({'stop': 1}, index=nltk.corpus.stopwords.words('english'))
sw.index.name='term_str'
sw.head()
if 'stop' not in VOCAB.columns:
    VOCAB = VOCAB.join(sw)
    VOCAB['stop'] = VOCAB['stop'].fillna(0).astype('int')
VOCAB

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\school\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,n,p,i,n_chars,max_pos_group,max_pos,n_pos_group,n_pos,stop
term_str,,,,,,,,,
the,36126,0.056064,4.156784,3,DT,DT,7.0,8.0,1
and,22280,0.034576,4.854073,3,CC,CC,7.0,10.0,1
to,18949,0.029407,5.087700,2,TO,TO,5.0,8.0,1
of,17802,0.027627,5.177783,2,IN,IN,2.0,2.0,1
i,15207,0.023600,5.405086,1,PR,PRP,7.0,9.0,1
...,...,...,...,...,...,...,...,...,...
houseto,1,0.000002,19.297534,7,NaN,NaN,NaN,NaN,0
mopboard,1,0.000002,19.297534,8,NaN,NaN,NaN,NaN,0
slaps,1,0.000002,19.297534,5,NaN,NaN,NaN,NaN,0
tramples,1,0.000002,19.297534,8,NaN,NaN,NaN,NaN,0
arabesque,1,0.000002,19.297534,9,NaN,NaN,NaN,NaN,0

In [8]:
from nltk.stem.porter import PorterStemmer
from nltk.stem.snowball import SnowballStemmer
from nltk.stem.lancaster import LancasterStemmer

p_stemmer = PorterStemmer()
s_stemmer = SnowballStemmer(ignore_stopwords=True, language='english')
l_stemmer = LancasterStemmer()
# VOCAB['p_stem'] = VOCAB.apply(lambda x: stemmer.stem(x.name), 1)
# VOCAB['p_stem'] = VOCAB.reset_index().term_str.apply(stemmer.stem)
VOCAB['porter_stem'] = [p_stemmer.stem(term_str) for term_str in VOCAB.index]
VOCAB['snowball_stem'] = [s_stemmer.stem(term_str) for term_str in VOCAB.index]
VOCAB['lancaster_stem'] = [l_stemmer.stem(term_str) for term_str in VOCAB.index]
VOCAB

,n,p,i,n_chars,max_pos_group,max_pos,n_pos_group,n_pos,stop,porter_stem,snowball_stem,lancaster_stem
term_str,,,,,,,,,,,,
the,36126,0.056064,4.156784,3,DT,DT,7.0,8.0,1,the,the,the
and,22280,0.034576,4.854073,3,CC,CC,7.0,10.0,1,and,and,and
to,18949,0.029407,5.087700,2,TO,TO,5.0,8.0,1,to,to,to
of,17802,0.027627,5.177783,2,IN,IN,2.0,2.0,1,of,of,of
i,15207,0.023600,5.405086,1,PR,PRP,7.0,9.0,1,i,i,i
...,...,...,...,...,...,...,...,...,...,...,...,...
houseto,1,0.000002,19.297534,7,NaN,NaN,NaN,NaN,0,houseto,houseto,houseto
mopboard,1,0.000002,19.297534,8,NaN,NaN,NaN,NaN,0,mopboard,mopboard,mopboard
slaps,1,0.000002,19.297534,5,NaN,NaN,NaN,NaN,0,slap,slap,slap
tramples,1,0.000002,19.297534,8,NaN,NaN,NaN,NaN,0,trampl,trampl,trampl
arabesque,1,0.000002,19.297534,9,NaN,NaN,NaN,NaN,0,arabesqu,arabesqu,arabesqu

# BOW

In [9]:
OHCO = ['book_id', 'chap_num', 'para_num', 'sent_num', 'token_num']
bags = dict(
    SENTS = OHCO[:4],
    PARAS = OHCO[:3],
    CHAPS = OHCO[:2],
    BOOKS = OHCO[:1]
)
bag = 'CHAPS'
BOW = ALL_TOKENS.groupby(bags[bag]+['term_str']).term_str.count().to_frame('n') 
BOW.head()

                            n
book_id chap_num term_str
43      1        a         79
                 able       1
                 about      9
                 abreast    1
                 accent     1

In [12]:
len(BOW)

149442

# DTM

In [9]:
DTCM = BOW.n.unstack(fill_value=0)
DTCM.head(10)

term_str          000  1  10  100  1018  1030  10th  11  1140  11th  ...  \
book_id chap_num                                                     ...
43      1           0  0   0    0     0     0     0   0     0     0  ...
        2           0  0   0    0     0     0     0   0     0     0  ...
        3           0  0   0    0     0     0     0   0     0     0  ...
        4           0  0   0    0     0     0     0   0     0     0  ...
        5           0  0   0    0     0     0     0   0     0     0  ...
        6           0  0   0    0     0     0     0   0     0     0  ...
        7           0  0   0    0     0     0     0   0     0     0  ...
        8           0  0   0    0     0     0     0   0     0     0  ...
        9           0  0   0    0     0     0     1   0     0     0  ...
175     1           0  2   0    0     0     0     0   0     0     0  ...

term_str          zoöphagy  zurich  à  æneis  æra  æt  ætat  æther  état  \
book_id chap_num
43      1                0       0  0      0    0   0     0      0     0
        2                0       0  1      0    0   0     0      0     0
        3                0       0  0      0    0   0     0      0     0
        4                0       0  0      0    0   0     0      0     0
        5                0       0  0      0    0   0     0      0     0
        6                0       0  0      0    0   0     0      0     0
        7                0       0  0      0    0   0     0      0     0
        8                0       0  0      0    0   0     0      0     0
        9                0       0  0      0    0   0     0      0     0
175     1                0       0  0      0    0   0     0      0     0

term_str          œdipus
book_id chap_num
43      1              0
        2              0
        3              0
        4              0
        5              0
        6              0
        7              0
        8              0
        9              0
175     1              0

[10 rows x 21504 columns]

In [11]:
# DOC = DTCM.sum(1).to_frame('n_tokens')
# DOC['n_types'] = DTCM.astype('bool').sum(1)
# DOC['pkr'] = DOC.n_types / DOC.n_tokens
# DOC = DOC.join(LIB[['author','title']])
# DOC.sort_values('pkr').head(20).style.background_gradient(cmap='YlGnBu')

# TFIDF

In [12]:
tf_method = 'double_norm'         # sum, max, log, double_norm, raw, binary
tf_norm_k = .5            # only used for double_norm
idf_method = 'standard'   # standard, max, smooth
gradient_cmap = 'YlGnBu'

In [13]:
print('TF method:', tf_method)

if tf_method == 'sum':
    TF = DTCM.T / DTCM.T.sum()

elif tf_method == 'smooth':
    TF = (DTCM.T / DTCM.T.sum()) + 1

elif tf_method == 'max':
    TF = DTCM.T / DTCM.T.max()
    
elif tf_method == 'log':
    TF = np.log2(1 + DTCM.T)
    
elif tf_method == 'raw':
    TF = DTCM.T
    
elif tf_method == 'double_norm':
    TF = ((DTCM.T + .5) / (DTCM.T.max() + .5)) + .5
    
elif tf_method == 'binary':
    TF = DTCM.T.astype('bool').astype('int')
    
TF = TF.T

TF method: double_norm

In [14]:
DF = DTCM.astype('bool').sum() 
DF

term_str
000        1
1         18
10         6
100        1
1018       1
          ..
æt         1
ætat       1
æther      3
état       1
œdipus     1
Length: 21504, dtype: int64

In [15]:
N = DTCM.shape[0]

In [16]:
print('IDF method:', idf_method)

if idf_method == 'standard':
    IDF = np.log2(N / DF)

elif idf_method == 'max':
    IDF = np.log2(DF.max() / DF) 

elif idf_method == 'plus':
    IDF = np.log2(N / DF) + 1

# This is what SciKit Learn uses
elif idf_method == 'smooth':
    IDF = np.log2((1 + N) / (1 + DF)) + 1

IDF method: standard

In [17]:
TFIDF = TF * IDF
TFIDF.head()

term_str               000         1        10       100      1018      1030  \
book_id chap_num
43      1         3.505731  1.407096  2.204774  3.505731  3.505731  3.505731
        2         3.501080  1.405230  2.201849  3.501080  3.501080  3.501080
        3         3.559439  1.428653  2.238552  3.559439  3.559439  3.559439
        4         3.510644  1.409069  2.207864  3.510644  3.510644  3.510644
        5         3.517548  1.411839  2.212206  3.517548  3.517548  3.517548

term_str              10th        11      1140      11th  ...  zoöphagy  \
book_id chap_num                                          ...
43      1         3.505731  2.204774  3.505731  3.505731  ...  3.505731
        2         3.501080  2.201849  3.501080  3.501080  ...  3.501080
        3         3.559439  2.238552  3.559439  3.559439  ...  3.559439
        4         3.510644  2.207864  3.510644  3.510644  ...  3.510644
        5         3.517548  2.212206  3.517548  3.517548  ...  3.517548

term_str            zurich         à     æneis       æra        æt      ætat  \
book_id chap_num
43      1         3.505731  2.499173  3.505731  3.505731  3.505731  3.505731
        2         3.501080  2.521789  3.501080  3.501080  3.501080  3.501080
        3         3.559439  2.537461  3.559439  3.559439  3.559439  3.559439
        4         3.510644  2.502676  3.510644  3.510644  3.510644  3.510644
        5         3.517548  2.507598  3.517548  3.517548  3.517548  3.517548

term_str             æther      état    œdipus
book_id chap_num
43      1         2.708053  3.505731  3.505731
        2         2.704460  3.501080  3.501080
        3         2.749541  3.559439  3.559439
        4         2.711848  3.510644  3.510644
        5         2.717181  3.517548  3.517548

[5 rows x 21504 columns]

## TFIDF_L2

In [37]:
def get_norm(X, p:int = 1):
    if p == 0:
        return X.astype(bool).astype(int)
    elif p > 0 and type(p) == int:
        unit_norm = (X**p).sum(1)**(1/p)
        return X.div(unit_norm, axis=0)
    else:
        raise ValueError("p must be an integer greater than 0")
    

TFIDF_L2 = get_norm(TFIDF, 2)

In [38]:
len(TFIDF_L2.columns)

21504

In [39]:
TFIDF_L2.columns

Index(['000', '1', '10', '100', '1018', '1030', '10th', '11', '1140', '11th',
       ...
       'zoöphagy', 'zurich', 'à', 'æneis', 'æra', 'æt', 'ætat', 'æther',
       'état', 'œdipus'],
      dtype='object', name='term_str', length=21504)

In [40]:
TFIDF_L2.to_csv('Data\TFIDF_L2.csv')

<>:1: SyntaxWarning: invalid escape sequence '\T'
<>:1: SyntaxWarning: invalid escape sequence '\T'
C:\Users\school\AppData\Local\Temp\ipykernel_77820\3752353867.py:1: SyntaxWarning: invalid escape sequence '\T'
  TFIDF_L2.to_csv('Data\TFIDF_L2.csv')

# Finish VOCAB table

In [18]:
VOCAB['df'] = DF
VOCAB['idf'] = IDF
VOCAB['tfidf_mean'] = TFIDF.mean()

In [20]:
VOCAB['dfidf'] = VOCAB.df * VOCAB.idf

In [21]:
VOCAB.to_csv('Data\VOCAB\FULL_VOCAB.csv')

<>:1: SyntaxWarning: invalid escape sequence '\V'
<>:1: SyntaxWarning: invalid escape sequence '\V'
C:\Users\school\AppData\Local\Temp\ipykernel_77820\1594210221.py:1: SyntaxWarning: invalid escape sequence '\V'
  VOCAB.to_csv('Data\VOCAB\FULL_VOCAB.csv')

In [22]:
VOCAB[['dfidf']].sort_values('dfidf', ascending=False)\
    .head(20).style.background_gradient(cmap='YlGnBu')

## Save derived tables

In [24]:
BOW['tf'] = TF.stack()
BOW['tfidf'] = TFIDF.stack()

In [25]:
DTCM.to_csv('Data\DTM.csv')
BOW.to_csv('Data\BOW.csv')
TFIDF.to_csv('Data\TFIDF.csv')

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:2: SyntaxWarning: invalid escape sequence '\B'
<>:3: SyntaxWarning: invalid escape sequence '\T'
<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:2: SyntaxWarning: invalid escape sequence '\B'
<>:3: SyntaxWarning: invalid escape sequence '\T'
C:\Users\school\AppData\Local\Temp\ipykernel_77820\4207633077.py:1: SyntaxWarning: invalid escape sequence '\D'
  DTCM.to_csv('Data\DTM.csv')
C:\Users\school\AppData\Local\Temp\ipykernel_77820\4207633077.py:2: SyntaxWarning: invalid escape sequence '\B'
  BOW.to_csv('Data\BOW.csv')
C:\Users\school\AppData\Local\Temp\ipykernel_77820\4207633077.py:3: SyntaxWarning: invalid escape sequence '\T'
  TFIDF.to_csv('Data\TFIDF.csv')