In [8]:
import pandas as pd

ALL_TOKENS = pd.read_csv('Data\CORPUS\FULL_CORPUS.csv')

<>:3: SyntaxWarning: invalid escape sequence '\C'
<>:3: SyntaxWarning: invalid escape sequence '\C'
C:\Users\school\AppData\Local\Temp\ipykernel_89888\2844328.py:3: SyntaxWarning: invalid escape sequence '\C'
  ALL_TOKENS = pd.read_csv('Data\CORPUS\FULL_CORPUS.csv')
C:\Users\school\AppData\Local\Temp\ipykernel_89888\2844328.py:3: DtypeWarning: Columns (5,6,9) have mixed types. Specify dtype option on import or set low_memory=False.
  ALL_TOKENS = pd.read_csv('Data\CORPUS\FULL_CORPUS.csv')

In [9]:
VOCAB = ALL_TOKENS.term_str.value_counts().to_frame('n')
VOCAB.index.name = 'term_str'

In [10]:
import numpy as np

VOCAB = ALL_TOKENS.term_str.value_counts().to_frame('n')
VOCAB.index.name = 'term_str'
VOCAB['p'] = VOCAB.n / VOCAB.n.sum()
VOCAB['i'] = -np.log2(VOCAB.p)
VOCAB['n_chars'] = VOCAB.index.str.len()
VOCAB

               n         p          i  n_chars
term_str
the        36126  0.056064   4.156784        3
and        22280  0.034576   4.854073        3
to         18949  0.029407   5.087700        2
of         17802  0.027627   5.177783        2
i          15207  0.023600   5.405086        1
...          ...       ...        ...      ...
houseto        1  0.000002  19.297534        7
mopboard       1  0.000002  19.297534        8
slaps          1  0.000002  19.297534        5
tramples       1  0.000002  19.297534        8
arabesque      1  0.000002  19.297534        9

[21504 rows x 4 columns]

In [12]:
VOCAB['max_pos_group'] = ALL_TOKENS[['term_str','pos_group']].value_counts().unstack(fill_value=0).idxmax(1)
VOCAB['max_pos'] = ALL_TOKENS[['term_str','pos']].value_counts().unstack(fill_value=0).idxmax(1)
VOCAB

               n         p          i  n_chars max_pos_group max_pos
term_str
the        36126  0.056064   4.156784        3            DT      DT
and        22280  0.034576   4.854073        3            CC      CC
to         18949  0.029407   5.087700        2            TO      TO
of         17802  0.027627   5.177783        2            IN      IN
i          15207  0.023600   5.405086        1            PR     PRP
...          ...       ...        ...      ...           ...     ...
houseto        1  0.000002  19.297534        7           NaN     NaN
mopboard       1  0.000002  19.297534        8           NaN     NaN
slaps          1  0.000002  19.297534        5           NaN     NaN
tramples       1  0.000002  19.297534        8           NaN     NaN
arabesque      1  0.000002  19.297534        9           NaN     NaN

[21504 rows x 6 columns]

In [14]:
TPM1 = ALL_TOKENS[['term_str','pos_group']].value_counts().unstack()
TPM1
VOCAB['n_pos_group'] = TPM1.count(1)
TPM2 = ALL_TOKENS[['term_str','pos']].value_counts().unstack()
VOCAB['n_pos'] = TPM2.count(1)

In [17]:
!pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Collecting nltk
  Downloading nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Collecting click (from nltk)
  Downloading click-8.3.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: joblib in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from nltk) (1.5.1)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.4.4-cp313-cp313-win_amd64.whl.metadata (41 kB)
Requirement already satisfied: tqdm in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\school\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.4-py3-none-any.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   ------------- -------------------------- 0.5/1.6 MB 348.1 kB/s eta 0:00:03
   -------------------- ------------------- 0.8/1.6 MB 534.6 kB/s eta 0:00:02
   -------------------- ------------------- 0.8/1.6 MB 534.6 kB/s eta 0:00:02
   --------------------------- ------------ 1.0/1.6 MB 517.9 kB/s eta 0:00:01
   --------------------------------- ------ 1.3/1.6 MB 633.7 kB/s eta 0:00:01
   --------------------------------- ------ 1.3/1.6 MB 633.7 kB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 628.1 kB/s  0:00:02
Downloading regex-2026.4.4-cp313-cp313-win_amd64.whl (277 kB)
Downloading click-8.3.2-py3-none-any.whl (108 kB)
Installing collected packages: regex, click, nltk

   ---------------------------------------- 0/3 [regex]
   ---------------------------------------- 0/3 [regex]
   ------------- -------------------------- 1/3 [click]
   ------------- -------------------------- 1/3 [click]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   ---------------------------------------- 3/3 [nltk]

Successfully installed click-8.3.2 nltk-3.9.4 regex-2026.4.4

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\school\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [19]:
import nltk
nltk.download('stopwords')
sw = pd.DataFrame({'stop': 1}, index=nltk.corpus.stopwords.words('english'))
sw.index.name='term_str'
sw.head()
if 'stop' not in VOCAB.columns:
    VOCAB = VOCAB.join(sw)
    VOCAB['stop'] = VOCAB['stop'].fillna(0).astype('int')
VOCAB

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\school\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

,n,p,i,n_chars,max_pos_group,max_pos,n_pos_group,n_pos,stop
term_str,,,,,,,,,
the,36126,0.056064,4.156784,3,DT,DT,7.0,8.0,1
and,22280,0.034576,4.854073,3,CC,CC,7.0,10.0,1
to,18949,0.029407,5.087700,2,TO,TO,5.0,8.0,1
of,17802,0.027627,5.177783,2,IN,IN,2.0,2.0,1
i,15207,0.023600,5.405086,1,PR,PRP,7.0,9.0,1
...,...,...,...,...,...,...,...,...,...
houseto,1,0.000002,19.297534,7,NaN,NaN,NaN,NaN,0
mopboard,1,0.000002,19.297534,8,NaN,NaN,NaN,NaN,0
slaps,1,0.000002,19.297534,5,NaN,NaN,NaN,NaN,0
tramples,1,0.000002,19.297534,8,NaN,NaN,NaN,NaN,0
arabesque,1,0.000002,19.297534,9,NaN,NaN,NaN,NaN,0

In [20]:
from nltk.stem.porter import PorterStemmer
from nltk.stem.snowball import SnowballStemmer
from nltk.stem.lancaster import LancasterStemmer

p_stemmer = PorterStemmer()
s_stemmer = SnowballStemmer(ignore_stopwords=True, language='english')
l_stemmer = LancasterStemmer()
# VOCAB['p_stem'] = VOCAB.apply(lambda x: stemmer.stem(x.name), 1)
# VOCAB['p_stem'] = VOCAB.reset_index().term_str.apply(stemmer.stem)
VOCAB['porter_stem'] = [p_stemmer.stem(term_str) for term_str in VOCAB.index]
VOCAB['snowball_stem'] = [s_stemmer.stem(term_str) for term_str in VOCAB.index]
VOCAB['lancaster_stem'] = [l_stemmer.stem(term_str) for term_str in VOCAB.index]
VOCAB

,n,p,i,n_chars,max_pos_group,max_pos,n_pos_group,n_pos,stop,porter_stem,snowball_stem,lancaster_stem
term_str,,,,,,,,,,,,
the,36126,0.056064,4.156784,3,DT,DT,7.0,8.0,1,the,the,the
and,22280,0.034576,4.854073,3,CC,CC,7.0,10.0,1,and,and,and
to,18949,0.029407,5.087700,2,TO,TO,5.0,8.0,1,to,to,to
of,17802,0.027627,5.177783,2,IN,IN,2.0,2.0,1,of,of,of
i,15207,0.023600,5.405086,1,PR,PRP,7.0,9.0,1,i,i,i
...,...,...,...,...,...,...,...,...,...,...,...,...
houseto,1,0.000002,19.297534,7,NaN,NaN,NaN,NaN,0,houseto,houseto,houseto
mopboard,1,0.000002,19.297534,8,NaN,NaN,NaN,NaN,0,mopboard,mopboard,mopboard
slaps,1,0.000002,19.297534,5,NaN,NaN,NaN,NaN,0,slap,slap,slap
tramples,1,0.000002,19.297534,8,NaN,NaN,NaN,NaN,0,trampl,trampl,trampl
arabesque,1,0.000002,19.297534,9,NaN,NaN,NaN,NaN,0,arabesqu,arabesqu,arabesqu

In [13]:
VOCAB.to_csv('Data\VOCAB\FULL_VOCAB.csv')

<>:1: SyntaxWarning: invalid escape sequence '\V'
<>:1: SyntaxWarning: invalid escape sequence '\V'
C:\Users\school\AppData\Local\Temp\ipykernel_89888\1594210221.py:1: SyntaxWarning: invalid escape sequence '\V'
  VOCAB.to_csv('Data\VOCAB\FULL_VOCAB.csv')